language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install .
  - pip install -r requirements-dev.txt
script:
  - nosetests
  - python setup.py sdist && pip install dist/ovh-*.tar.gz && cd /tmp && python -c 'import ovh; ovh.Client("ovh-eu").get("/auth/time", _need_auth=False)'
after_success:
    coveralls
sudo: false

